---
# Select the type of API version and type of service/object
apiVersion: v1
kind: Service
# Metadata for name
metadata:  
  name: nginx-svc
  namespace: default  
# Specificaition to include ports Selector to connecto to the deployment
spec:  
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 80

# Let's define the selector and label to connect to nginx deployment
  selector:
    app: nginx # this label connects this service to deployment
  
  # Creating LoadBalancer type of deployment
  type: LoadBalancer 
